### ISSUE TITLE
运行-uf domain.txt  提示必须是字符串或字符串列表

### ISSUE THREAD

**Issue by sharcmz** [s1g0day/ICP_Query_Batch#1]
python 0.icp_query.py -uf domain.txt
python环境 Python 3.10.9

![image](https://github.com/s1g0day/ICP_query_s1g0day/assets/81364075/a42e5338-96c5-4747-9b01-4913239b6959)

**Comment by s1g0day** [comment]
包括gov网站也无法使用缩写进行查询，只能使用完整的公司名称。但你可以使用根域名:baidu.com，会自动识别公司名称并根据公司名称获取备案域名
